// Regenerates content/scripts/zm-data.js from the canonical repo CSVs.
// Reads ../../data/*.csv (read-only) and writes into the plugin subfolder only.
// Run: node tools/gen-data.mjs   (from the plugin/ dir)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = resolve(here, "..", "..", "data");
const outFile = resolve(here, "..", "content", "scripts", "zm-data.js");

// Minimal CSV: no quoted fields in these files; aliases use "|" (never ","), so a
// plain comma split is safe. Trailing optional column (write_as) may be absent.
function parseCsv(text) {
  const lines = text.replace(/\r\n/g, "\n").split("\n").filter((l) => l.length);
  const header = lines.shift().split(",");
  return lines.map((line) => {
    const cells = line.split(",");
    const row = {};
    header.forEach((h, i) => (row[h.trim()] = (cells[i] ?? "").trim()));
    return row;
  });
}

const rankRows = parseCsv(readFileSync(resolve(dataDir, "venue_rankings.csv"), "utf-8"));
const RANKINGS = rankRows.map((r) => ({
  canonical: r.canonical,
  kind: r.kind || "conference",
  core_tier: r.core_tier || "",
  aliases: r.aliases || "",
  write_as: r.write_as || "",
}));

const ovRows = parseCsv(readFileSync(resolve(dataDir, "overrides.csv"), "utf-8"));
const OVERRIDES = {};
for (const r of ovRows) {
  const aid = (r.arxiv_id || "").trim();
  if (!aid) continue;
  const year = /^\d+$/.test((r.year || "").trim()) ? parseInt(r.year, 10) : null;
  OVERRIDES[aid] = { canonical: (r.canonical || "").trim(), year };
}

const banner = `// AUTO-GENERATED by tools/gen-data.mjs from ../../data/*.csv — do not edit by hand.
// Venue ranking + override tables, embedded so the resolver needs no file IO at runtime.
// Loaded as a classic subscript in Zotero (top-level vars share the plugin scope) and
// as a CommonJS module in Node tests (module.exports).`;

const body = `${banner}
var ZM_RANKINGS = ${JSON.stringify(RANKINGS, null, 2)};
var ZM_OVERRIDES = ${JSON.stringify(OVERRIDES, null, 2)};
if (typeof module !== "undefined" && module.exports) {
  module.exports = { RANKINGS: ZM_RANKINGS, OVERRIDES: ZM_OVERRIDES };
}
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, body, "utf-8");
console.log(`wrote ${outFile}: ${RANKINGS.length} venues, ${Object.keys(OVERRIDES).length} overrides`);
